# This workflow the tests

name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with: 
           python-version: 3.12

    - name: Instalando as Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Inicializando a biblioteca Browser
      run: rfbrowser init

    - name: Rodandos os testes E2E
      run: robot -d ./logs -i smoke tests
