# This workflow the tests

name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

# Instalando a bliblioteca Node.JS, pq o playwright (Browswer) precisa dela.
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

# Instalando a bliblioteca Python, pq o robot framework precisa dela.
    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with: 
           python-version: 3.12

    - name: Instalando as Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Inicializando a biblioteca Browser
      run: rfbrowser init

# Rodandos os testes dos projeto.
    - name: Rodandos os testes E2E
      run: robot -d ./logs -i smoke tests

    - name: Gerando o Report no Robot   
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}  #Variavel padrao do github, sempre usar assim.
      # Tem que dar deixar configurado a permisão no github "Settings > Actions> General > em "Workflow permissions" clicar em "Read and write permissions")".         
        report_path: logs

  # Para guardar os reports e poder baixalos depois     
    - name: Upload Report
      uses: actions/upload-artifact@v4.4.3
      with: 
        name: Resultado dos testes
        path: logs
